### ISSUE TITLE
"/aac <argument>" is not displaying the replacement

### ISSUE THREAD

**Issue by alexmarkey** [Photon-GitHub/AACHider#7]
### Issue Description
Players are able to type "/aac {argument}" and as a result AAC will output the following http://prntscr.com/p2yu2z letting players know we are running AAC.  In the AACPlus config, we have enabled all the correct aspects to hide the AAC command.  If players are to simply type "/aac" with no additional arguments, it will successfully display the replacement message, its only upon adding a argument to the command that it fails.

### Core Information
**Server version**: 
TacoSpigot 1.8.8

**AAC version**: 
4.1.8-b3

**AACadditionPro version**: 
N/A (We do not use it on our server)

**AACPlus version**: 
2.0.5

**ProtocolLib version**: 
4.3.0

**Plugin list**: (chat or actionbar plugins?)
ProtocolLib, AAC, AACPlus
We have reproduced the bug localhost with simply those above 3 plugins.

### Special Environment Info
**ViaVersion version**: Insert version or say N/A
N/A

**ProtocolSupport version**: 
N/A

**ViaBackwards version**: 
N/A

**BungeeCord plugins**: (chat or actionbar plugins?)
N/A

### Configurations
Post your AAC-Hider config **and** AAC language.yml if altered. Or say "default" if untouched.
default

AACPlus Config: 
```
https://pastebin.com/ejxAYHfH
```

**Comment by Photon-GitHub** [comment]
Fixed as of 2.1.0

**Comment by alexmarkey** [comment]
This is still not fixed on 2.1.0.
I noticed you mentioned that the loophole was only ofr unknown commands, however even real existing commands do not display the replacement.

/aac {unknown-argument} = http://prntscr.com/p6auxs
/aac reload = http://prntscr.com/p6av16

**Comment by alexmarkey** [comment]
As requested, here is more info on the issue:

Spigot jar I am using:
https://yivesmirror.com/files/paper/PaperSpigot-1.8.8-R0.1-SNAPSHOT-latest.jar

AAC Version: 4.2.1
AACPlus Version: 2.1.1
ProtocolLib Version: 4.3.0
AAC Config: https://pastebin.com/2iXWaGB0 
AACPlus Confg: https://pastebin.com/SUQUkgqK
(Both of the above configs are literally the default generated configs for testing sake)
My test server has ONLY the above 3 plugins.

Upon logging onto the test server with a non-op account, if this account runs the command "/aac reload" they receive the following message in chat http://prntscr.com/pcb57w

**Comment by HexedHero** [comment]
Not fixed
https://cdn.hexedhero.com/u/ASWKX9rQql.jpg

**Comment by CeIebrimbor** [comment]
@Photon-GitHub

**Comment by Photon-GitHub** [comment]
Fixed in 2.2.0

**Comment by Keviro** [comment]
Still a thing in 2.2.0.

![H7asqxy](https://user-images.githubusercontent.com/25409956/72835979-037f8c00-3c8c-11ea-8096-d3b1b59a3ad0.png)

![Y6CUJTI](https://user-images.githubusercontent.com/25409956/72835929-eba80800-3c8b-11ea-82b9-5d756104406b.png)

**Comment by Photon-GitHub** [comment]
In that case please share your config. I have tested this quite thoroughly with the default config.

**Comment by Keviro** [comment]
These are the newest InstaBan configs available without any changes.
AAC v4.3.5 | InstaBan | 1 -
AACadditionPro v6.0.0 | InstaBan | 1 -

and the default config from aacplus. 
Since this was my testserver there were no other plugins installed either, exept WorldEdit and the needed ones of course, protocollib and conditionalcommands.

**Comment by Photon-GitHub** [comment]
Caused by obfuscation issues. Please redownload.
